sudo: required
services:
 - docker

before_install:
 - docker build -t manojsahukari/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true manojsahukari/react-test npm test -- --coverage

after-success:
 - docker build -t manojsahukari/multi-client ./client
 - docker build -t manojsahukari/multi-nginx ./nginx
 - docker build -t manojsahukari/multi-server ./server
 - docker build -t manojsahukari/multi-worker ./worker

 #login to docker cli take images and push it to docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push manojsahukari/multi-client
 - docker push manojsahukari/multi-nginx
 - docker push manojsahukari/multi-server
 - docker push manojsahukari/multi-worker
